// Every file in public/audio is generated by scripts/generate-audio.mts and
// normalized to a -1 dBFS peak. The gains below are applied on top of that peak.
export const dbToGain = (decibels: number): number => 10 ** (decibels / 20);

export const levels = {
  musicDb: -24,
  uiDb: -12,
} as const;

export const music = {
  file: 'audio/music-bed.wav',
  fadeInFrames: 90,
  fadeOutFrames: 150,
} as const;

export type SoundName =
  | 'click'
  | 'pop'
  | 'whoosh'
  | 'impact'
  | 'data'
  | 'success';

type SoundDefinition = {
  file: string;
  seconds: number;
  use: string;
};

export const sounds: Record<SoundName, SoundDefinition> = {
  click: { file: 'audio/click.wav', seconds: 0.08, use: 'Cursor clicks on buttons and menus' },
  pop: { file: 'audio/pop.wav', seconds: 0.25, use: 'Cards, callouts and dialogs appearing' },
  whoosh: { file: 'audio/whoosh.wav', seconds: 0.75, use: 'Scene transitions' },
  impact: { file: 'audio/impact.wav', seconds: 1.6, use: 'Major feature and brand reveals' },
  data: { file: 'audio/data.wav', seconds: 0.55, use: 'Numbers and records updating' },
  success: { file: 'audio/success.wav', seconds: 1.2, use: 'Order placed, order completed' },
};

// Transition whooshes start slightly early so their swell peaks mid-transition.
export const WHOOSH_LEAD_FRAMES = 4;
