import { cookies } from "next/headers"
import type { Metadata } from 'next'
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from '@/components/AppSidebar'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import Image from 'next/image'
import { useSidebarStore } from '@/stores/sidebarStore'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "false"

  // const { isCollapsed } = useSidebarStore((state) => ({
  //   isCollapsed: state.isCollapsed
  // }))

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          
          {/* Fixed Header */}
          <header className="fixed top-0 left-0 w-full bg-white shadow-sm z-50 h-16 flex items-center px-4">
            <SignedOut>
              <div className="flex justify-between w-full">
                <div className="text-2xl font-semibold">Business Tracker</div>
                <div className="flex items-center gap-2">
                  <SignInButton />
                  
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Sign Up
                    </button>
                  </SignUpButton>
                </div>
              </div>
            </SignedOut>
  
            <SignedIn>
              <div className="flex justify-between w-full">
                <div className="bg-zinc-50 border-1 border-teal-600 rounded-lg py-1">
                  <Image
                    src="/logo-with-title.png"
                    alt="logo"
                    width={200}
                    height={200}
                  />
                </div>
            
                <UserButton />
              </div>
            </SignedIn>
          </header>
  
          {/* Sidebar + Main layout */}
          <SidebarProvider>
            <div className="flex flex-row w-screen pt-13">
              <AppSidebar />

              <div className="w-full bg-gray-50 min-h-[calc(100vh-3rem)] p-4">
                {children}
              </div>
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}